# Generated by Django 5.0.6 on 2024-09-08 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_rename_second_name_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='head_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='sudy_group',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группа к которой пренадлежит пользователь. Пользователь получит все права группы к которой пренадлежит', related_name='myuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Отдельные права для конкретногот пользователя (не используются)', related_name='myuser_set', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.IntegerField()),
                ('litera', models.CharField(max_length=1)),
                ('head_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('parents', models.ManyToManyField(related_name='parent', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='users.grade'),
        ),
    ]
