User_roles = {
    'school_administration': 'Школьная администрация',
    'system_administration': 'Системный администратор',
    'teacher': 'Учитель',
    'head_teacher': 'Классный руководитель',
    'parent': 'Родтель',
    'school_accountant': 'Бухгалтер',
    'canteen_worker': 'Работник столовой',
    'suggestions_moderator': 'Модератор предложений',
    'head_of_security': 'Заведующий безопасности',
    'head_of_household': 'Заведующий хозяйством',
    'technician': 'Техник',
    'household_worker': 'Хоз рабочий',
    'head_of_press_center': 'Глава пресс-центра',
    'memeber_of_press_centre': 'Участник пресс-центра',
    'head_of_transportation': 'Глава развозки',
    '': 'Водитель развозки',
}
