# Generated by Django 5.0.6 on 2025-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('suggestions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='max_votes_against',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='max_votes_for',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='restricted_to_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
