# Generated by Django 5.0.6 on 2024-09-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KnowledgeBase', '0001_initial'),
        ('users', '0004_remove_user_head_teacher_user_sudy_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='users.grade'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KnowledgeBase.materialtype'),
        ),
        migrations.AddField(
            model_name='favoritematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='KnowledgeBase.studymaterial'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='KnowledgeBase.subject'),
        ),
    ]
