# Generated by Django 5.0.6 on 2025-01-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dinner_MealSet',
            new_name='BreakfastMealSet',
        ),
        migrations.RenameModel(
            old_name='lunch_MealSet',
            new_name='DinnerMealSet',
        ),
        migrations.RenameModel(
            old_name='breakfast_MealSet',
            new_name='LunchMealSet',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='callaories',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='callories',
            new_name='calories',
        ),
    ]
