# Generated by Django 5.0.6 on 2024-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit_note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
