# Generated by Django 5.0.6 on 2024-07-26 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_notes', '0002_exit_note_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit_note',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_note_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exit_note',
            name='denied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_note_denied_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exit_note',
            name='parent_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_note_parent_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exit_note',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='exit_note',
            name='security_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_note_security_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exit_note',
            name='teacher_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_note_teacher_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
