# Generated by Django 5.0.6 on 2024-08-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_rename_lilera_school_schedule_litera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='name',
            new_name='lesson_type',
        ),
        migrations.AddField(
            model_name='lessons',
            name='taught_from',
            field=models.IntegerField(default=1),
        ),
    ]
