name: Super-linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-django
              flake8 --max-line-length=400 --exclude=migrations.
      # Run Black (auto-formatting) using Python 3.12.2
      - name: Run Black
        uses: docker://python:3.12.2
        with:
          args: |
            pip install black 
              black --check --diff .
      # Run Mypy (type checking) using Docker (Python 3.12.2)
      - name: Run Mypy
        uses: docker://python:3.12.2
        with:
          args: |
            pip install mypy 
              mypy schollarsite1/
      # Run HTMLLint using Docker (Node.js)
      - name: Run HTMLLint
        uses: docker://node:16
        with:
          args: |
            npm install -g htmlhint 
              htmlhint ./**/*.html
      # Run Stylelint (CSS Linting) using Docker (Node.js)
      - name: Run Stylelint
        uses: docker://node:16
        with:
          args: |
            npm install -g stylelint 
              stylelint "**/*.css"
      # Run ESLint (JavaScript Linting) using Docker (Node.js)
      - name: Run ESLint
        uses: docker://node:16
        with:
          args: |
            npm install -g eslint 
              eslint ./**/*.js

  deploy:
    runs-on: ubuntu-latest
    needs: super-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no admindev@89.218.24.244 << 'EOF'
            cd ~/schollarsite1  
            git pull
            docker-compose down && docker-compose up -d  
          EOF