name: Super-linter

on: push

jobs:
  lint:
    name: Lint and Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run Flake8 (with Django plugin) using Python 3.12.2
      - name: Run Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-django
              flake8 --max-line-length=329 --exclude=migrations.

      # Run Pylint using Python 3.12.2
      - name: Run Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pylint --max-line-length=329 --ignore=migrations .

      # Run Black (auto-formatting) using Python 3.12.2
      - name: Run Black
        run: |
          python -m pip install --upgrade pip
          pip install black
          black --check --diff --exclude "migrations" .

      # Run Mypy (type checking) using Python 3.12.2
      - name: Run Mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          mypy --exclude "tests|migrations" schollarsite1/

      # Run HTMLLint using Node.js
      - name: Run HTMLLint
        run: |
          npm install -g htmlhint
          htmlhint ./**/*.html

      # Run Stylelint (CSS Linting) using Node.js
      - name: Run Stylelint
        run: |
          npm install -g stylelint
          stylelint "**/*.css"

      # Run ESLint (JavaScript Linting) using Node.js
      - name: Run ESLint
        run: |
          npm install -g eslint
          eslint ./**/*.js

  deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no admindev@89.218.24.244 << 'EOF'
            cd ~/schollarsite1  
            git pull
            docker-compose down && docker-compose up -d  
          EOF