name: Super-linter

on: push

jobs:
  super-lint:
    name: Lint code base 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-django
              flake8 --max-line-length=400 --exclude=migrations.

      - name: Run Mypy
        run: |
            python -m pip install --upgrade pip
            pip install mypy 
              mypy --ignore-missing-imports --exclude '.*migrations.*' .

  deploy:
    runs-on: ubuntu-latest
    needs: super-lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: SSH and run commands
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
        run: |
          echo "$PRIVATE_KEY" > private_key.pem 
          chmod 600 private_key.pem 
          ssh -o StrictHostKeyChecking=no -i private_key.pem admindev@y89.218.24.244 <<EOF
          cd schollarsite1
          git pull 
          docker-compose up -d --build
          EOF
          rm -f private_key.pem # Remove the private key file after use for security
    permissions:
      contents: read
      actions: write
      id-token: write