name: Super-linter

on: push

jobs:
  super-lint:
    name: Lint code base 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-django
              flake8 --max-line-length=400 --exclude=migrations.

      - name: Run Mypy
        run: |
            python -m pip install --upgrade pip
            pip install mypy 
              mypy --ignore-missing-imports --exclude '.*migrations.*' .

  deploy:
    runs-on: ubuntu-latest
    needs: super-lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: get SSH ad set permissions
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 
            chmod 600 ~/.ssh/id_ed25519

      - name: Deploy with SCP
        run: |
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 -r admindev@89.218.24.244
            cd schollarsite1
            git pull 
            docker-compose up -d --build

