name: Super-linter

on: push

jobs:
  lint:
    name: Lint and Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-linter
        uses: github/super-linter@v3
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no admindev@89.218.24.244 << 'EOF'
            cd ~/schollarsite1  
            git pull
            docker-compose down && docker-compose up -d  
          EOF